---
- name: Check if golang is installed
  shell: go version
  register: go_bin
  ignore_errors: true

- name: Download golang
  get_url:
    url: https://golang.org/dl/go1.15.2.linux-armv6l.tar.gz
    dest: /tmp/go.tar.gz
  when: go_bin.rc != 0

- name: Unarchive Golang
  become: true
  unarchive:
    src: /tmp/go.tar.gz
    dest: /opt
    remote_src: true
  when: go_bin.rc != 0

- name: Add go bin to PATH
  lineinfile:
      path: ~/.bashrc
      line: 'PATH=$PATH:/opt/go/bin'
  when: go_bin.rc != 0