---
- name: Update apt
  become: true
  apt: 
    upgrade: dist
    update_cache: yes

- name: Remove useless packages from the cache
  become: true
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

- name: Install common used software
  become: true
  apt:
    name: {{ packages }}
  vars:
    packages:
      - vim

- name: Copy configuration for raspberry pi
  become: true
  template:
    src: templates/config.txt
    dest: /boot/config.txt
    user: root
    group: root
    mode: 0644
