---
- name: Check if composer is installed
  shell: composer --version
  register: composer_bin
  ignore_errors: true

- name: Download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
  when: composer_bin.rc != 0

- name: Configure composer
  become: true
  shell: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
  when: composer_bin.rc != 0

- name: Remove composer installer
  file:
    path: /tmp/composer-setup.php
    state: absent
  when: composer_bin.rc != 0

- name: Update composer
  become: true
  shell: composer selfupdate
  when: composer_bin.rc == 0

- name: Add composer bin to path
  lineinfile:
    path: /home/pi/.bashrc
    line: 'export PATH=$PATH:~/.config/composer/vendor/bin/'
  when: composer_bin.rc == 0