---
- name: Check if php is installed
  shell: php --version
  register: php_bin
  ignore_errors: true

- name: Download apt cert
  become: true
  get_url:
    url: https://packages.sury.org/php/apt.gpg
    dest: /etc/apt/trusted.gpg.d/php.gpg
    owner: root
    group: root

- name: Add PHP repo to APT
  become: true
  template:
    src: templates/10-buster.list
    dest: /etc/apt/sources.list.d/10-buster.list
    owner: root
    group: root
    mode: 0644
  when: php_bin.rc != 0

- name: Configure APT to use new repo
  become: true
  template:
    src: templates/10-buster
    dest: /etc/apt/preferences.d/10-buster
    owner: root
    group: root
    mode: 0644
  when: php_bin.rc != 0

- name: Update apt
  become: true
  apt: 
    update_cache: yes
  when: php_bin.rc != 0

- name: Install PHP
  become: true
  apt:
    name: "{{ packages }}"
    default_release: buster
  vars:
    packages:
      - php7.4-fpm 
      - php7.4-curl 
      - php7.4-gd 
      - php7.4-intl 
      - php7.4-mbstring 
      - php7.4-mysql 
      - php7.4-imap 
      - php7.4-opcache 
      - php7.4-sqlite3 
      - php7.4-xml 
      - php7.4-xmlrpc 
      - php7.4-zip 
      - php-apcu
  when: php_bin.rc != 0

- include_tasks: composer.yml
- include_tasks: packages.yml
